name: Foundry CI & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CHAIN_ID: 8453 # Base Mainnet (adjust as needed)
  RPC_URL: ${{ secrets.RPC_URL }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  DEPLOY_TAG: v1.0.0
  REGISTRY_NAME: boomchainlabs-registry

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠 Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: 🔎 Run Tests with Gas Report
        run: forge test --gas-report

      - name: 🚀 Deploy Registry Contract (if secrets are set)
        if: ${{ secrets.PRIVATE_KEY != '' && secrets.RPC_URL != '' }}
        run: |
          forge script script/DeployRegistry.s.sol:DeployRegistry \
            --rpc-url $RPC_URL \
            --private-key $PRIVATE_KEY \
            --broadcast \
            --verify \
            --etherscan-api-key $ETHERSCAN_API_KEY \
            --chain-id $CHAIN_ID

      - name: ✅ Complete
        run: echo "Deployment pipeline executed successfully ✅"
